services:
    - docker
   
script:
    - docker build -t sonbz/udagram-api-feed:v2 ./udagram-api-feed
    - docker build -t sonbz/udagram-api-user:v2 ./udagram-api-user
    - docker build -t sonbz/udagram-reverseproxy:v2 ./udagram-reverseproxy
    - docker build -t sonbz/udagram-frontend:v2 ./udagram-frontend
    

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push sonbz/udagram-api-feed:v2
    - docker push sonbz/udagram-reverseproxy:v2
    - docker push sonbz/udagram-api-user:v2
    - docker push sonbz/udagram-frontend:v2