services:
    - docker
   
script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_USERNAME/udagram-api-feed:v1 ./udagram-api-feed
    - docker build -t $DOCKER_USERNAME/udagram-api-user:v1 ./udagram-api-user
    - docker build -t $DOCKER_USERNAME/reverseproxy:v1 ./reverseproxy
    - docker build -t $DOCKER_USERNAME/udagram-frontend:v1 ./udagram-frontend
    - docker push $DOCKER_USERNAME/udagram-api-feed:v1
    - docker push $DOCKER_USERNAME/reverseproxy:v1
    - docker push $DOCKER_USERNAME/udagram-api-user:v1
    - docker push $DOCKER_USERNAME/udagram-frontend:v1
    