language:node_js
node_js:
    - 13
    
services:
    - docker

install:
    - echo "run project 3"
   
script:
    - docker build -t udagram-api-feed ./udagram-api-feed
    - docker build -t reverseproxy ./reverseproxy
    - docker build -t udagram-api-user ./udagram-api-user
    - docker build -t udagram-frontend ./udagram-frontend

after_success:
    - docker tag udagram-api-feed sonbz/udagram-api-feed:v1
    - docker tag reverseproxy sonbz/reverseproxy:v1
    - docker tag udagram-api-user sonbz/udagram-api-user:v1
    - docker tag udagram-frontend sonbz/udagram-frontend:v1
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push sonbz/udagram-api-feed:v1
    - docker push sonbz/reverseproxy:v1
    - docker push sonbz/udagram-api-user:v1
    - docker push sonbz/udagram-frontend:v1